some changes v6

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -44,10 +44,15 @@ jobs:
              with:
                 python-version: '3.11'
 
+           - name: Check requirements.txt
+             run: |
+                ls -la
+                test -f requirements.txt || (echo "requirements.txt not found" && exit 1)
+
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
-                 pip install -r app/requirements.txt
+                 pip install -r requirements.txt
 
            - name: Run migrations
              run: python manage.py migrate
